### ISSUE TITLE
Querying doesn't seem to work

### ISSUE THREAD

**Issue by HarshaVardhanJ** [Uzay-G/archivy#22]
I've started both Archivy and Elasticsearch using Docker Compose. I've checked to make sure that Archivy is able to connect to Elasticsearch. I added a few notes and folders in Archivy. When I try to query them from the command line using
```shell
 $ curl localhost:9200/_search?q="note"
```

I get a valid response like this:
```
{"took":9,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":{"value":2,"relation":"eq"},"max_score":0.19100355,"hits":[{"_index":"dataobj","_type":"_doc","_id":"2","_score":0.19100355,"_source":{"title":"New Note","content":"","desc":"New note inside newFolder","tags":["test"]}},{"_index":"dataobj","_type":"_doc","_id":"1","_score":0.18232156,"_source":{"title":"Test Note","content":"","desc":"test note with test description","tags":["test"]}}]}}
```

But when I try the query from the search bar, nothing turns up. I've pasted the logs below:
```
[2020-08-20 17:05:31,140] ERROR in app: Exception on /search [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/main/routes.py", line 107, in search_elastic
    search_results = query_index("dataobj", query)
  File "/usr/src/app/main/search.py", line 20, in query_index
    search = ELASTIC_SEARCH.search(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 92, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 1618, in search
    return self.transport.perform_request(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/transport.py", line 355, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 252, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/connection/base.py", line 281, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', '[multi_match] analyzer [rebuilt_standard] not found')
172.19.0.1 - - [20/Aug/2020 17:05:31] "GET /search?query=note HTTP/1.1" 500 -
```

Judging from the last log line `GET /search?query=note HTTP/1.1" 500`, could it be that the query format is incorrect?

It worked when I try to send a query manually using `curl` like so:
```shell
curl localhost:9200/_search?q="note"
```

Could it be that `search?query=` will need to be changed to `_search?q=`?

**Comment by Uzay-G** [comment]
Hmm, the way it works is when you launch the app, it checks if the `dataobj` index is created, and if it is not, it loads the elasticsearch.json config and creates the index here:
https://github.com/Uzay-G/archivy/blob/9beadc813b8ece7c668fd7dcc1be59ce50782043/main/__init__.py#L18-L25

So maybe try deleting the test note, and running `curl -X DELETE http://localhost:9200/dataobj`. Then could you send me the output of running the app so I can see how the print statements above get processed?

Thanks

**Comment by Uzay-G** [comment]
Please tell me what happens with this because it is a major problem.

**Comment by HarshaVardhanJ** [comment]
Apologies for the delay. I'll be more detailed here.

## Initial Steps Taken

After starting up Archivy with Elasticsearch, here are the steps I took:

- Added a new note titled `Test Note` with the tag `test`.
- Added a new note titled `New Note` with the tag `test`.
- Added a new folder titled `TestFolder` with the tag `test`.
- Added a new note inside `TestFolder` titled `New Note` with the tag `test`.
- Queried for the term `test` in the search bar and was returned no results.
- Back to the home page.
- Viewed the first note I created.

Then, I queried the term `test` in the search bar, and nothing showed up. Here are the complete logs:

```
/usr/src/app/entrypoint.sh: line 193: pkill: command not found
Traceback (most recent call last):
  File "check_changes.py", line 2, in <module>
    from main import search, models
  File "/usr/src/app/main/__init__.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
 * Serving Flask app "archivy.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
/usr/local/lib/python3.8/site-packages/scss/selector.py:26: FutureWarning: Possible nested set at position 329
  SELECTOR_TOKENIZER = re.compile(r'''
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)

172.18.0.1 - - [21/Aug/2020 02:47:28] "GET /index HTTP/1.1" 200 -
172.18.0.1 - - [21/Aug/2020 02:47:29] "GET /static/main.css HTTP/1.1" 304 -
172.18.0.1 - - [21/Aug/2020 02:49:13] "GET /notes/new HTTP/1.1" 200 -
172.18.0.1 - - [21/Aug/2020 02:49:27] "POST /notes/new HTTP/1.1" 302 -
172.18.0.1 - - [21/Aug/2020 02:49:27] "GET /dataobj/1 HTTP/1.1" 200 -
172.18.0.1 - - [21/Aug/2020 02:49:39] "GET /index HTTP/1.1" 200 -
172.18.0.1 - - [21/Aug/2020 02:49:46] "GET /notes/new HTTP/1.1" 200 -
172.18.0.1 - - [21/Aug/2020 02:50:02] "POST /notes/new HTTP/1.1" 302 -
172.18.0.1 - - [21/Aug/2020 02:50:02] "GET /dataobj/2 HTTP/1.1" 200 -
172.18.0.1 - - [21/Aug/2020 02:50:07] "GET /index HTTP/1.1" 200 -
172.18.0.1 - - [21/Aug/2020 02:50:14] "POST /folders/new HTTP/1.1" 200 -
172.18.0.1 - - [21/Aug/2020 02:50:26] "GET /notes/new HTTP/1.1" 200 -
172.18.0.1 - - [21/Aug/2020 02:51:00] "POST /notes/new HTTP/1.1" 302 -
172.18.0.1 - - [21/Aug/2020 02:51:00] "GET /dataobj/3 HTTP/1.1" 200 -
172.18.0.1 - - [21/Aug/2020 02:51:03] "GET /index HTTP/1.1" 200 -
[2020-08-21 02:51:15,146] ERROR in app: Exception on /search [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/main/routes.py", line 107, in search_elastic
    search_results = query_index("dataobj", query)
  File "/usr/src/app/main/search.py", line 20, in query_index
    search = ELASTIC_SEARCH.search(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 92, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 1618, in search
    return self.transport.perform_request(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/transport.py", line 355, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 252, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/connection/base.py", line 281, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', '[multi_match] analyzer [rebuilt_standard] not found')
172.18.0.1 - - [21/Aug/2020 02:51:15] "GET /search?query=t HTTP/1.1" 500 -
[2020-08-21 02:51:15,185] ERROR in app: Exception on /search [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/main/routes.py", line 107, in search_elastic
    search_results = query_index("dataobj", query)
  File "/usr/src/app/main/search.py", line 20, in query_index
    search = ELASTIC_SEARCH.search(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 92, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 1618, in search
    return self.transport.perform_request(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/transport.py", line 355, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 252, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/connection/base.py", line 281, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', '[multi_match] analyzer [rebuilt_standard] not found')
172.18.0.1 - - [21/Aug/2020 02:51:15] "GET /search?query=te HTTP/1.1" 500 -
[2020-08-21 02:51:15,202] ERROR in app: Exception on /search [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/main/routes.py", line 107, in search_elastic
    search_results = query_index("dataobj", query)
  File "/usr/src/app/main/search.py", line 20, in query_index
    search = ELASTIC_SEARCH.search(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 92, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 1618, in search
    return self.transport.perform_request(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/transport.py", line 355, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 252, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/connection/base.py", line 281, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', '[multi_match] analyzer [rebuilt_standard] not found')
172.18.0.1 - - [21/Aug/2020 02:51:15] "GET /search?query=tes HTTP/1.1" 500 -
[2020-08-21 02:51:15,295] ERROR in app: Exception on /search [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/main/routes.py", line 107, in search_elastic
    search_results = query_index("dataobj", query)
  File "/usr/src/app/main/search.py", line 20, in query_index
    search = ELASTIC_SEARCH.search(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 92, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 1618, in search
    return self.transport.perform_request(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/transport.py", line 355, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 252, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/connection/base.py", line 281, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', '[multi_match] analyzer [rebuilt_standard] not found')
172.18.0.1 - - [21/Aug/2020 02:51:15] "GET /search?query=test HTTP/1.1" 500 -
[2020-08-21 02:54:06,165] ERROR in app: Exception on /search [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/main/routes.py", line 107, in search_elastic
    search_results = query_index("dataobj", query)
  File "/usr/src/app/main/search.py", line 20, in query_index
    search = ELASTIC_SEARCH.search(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 92, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 1618, in search
    return self.transport.perform_request(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/transport.py", line 355, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 252, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/connection/base.py", line 281, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', '[multi_match] analyzer [rebuilt_standard] not found')
172.18.0.1 - - [21/Aug/2020 02:54:06] "GET /search?query=testA HTTP/1.1" 500 -
172.18.0.1 - - [21/Aug/2020 02:54:15] "GET /index HTTP/1.1" 200 -
172.18.0.1 - - [21/Aug/2020 02:55:06] "GET /dataobj/1 HTTP/1.1" 200 -
172.18.0.1 - - [21/Aug/2020 02:55:08] "GET /index HTTP/1.1" 200 -
172.18.0.1 - - [21/Aug/2020 02:55:10] "GET /notes/new HTTP/1.1" 200 -
172.18.0.1 - - [21/Aug/2020 02:55:12] "GET /index HTTP/1.1" 200 -
```

## Trying your suggestion

I did the following in order:
- Deleted all notes and folders from the UI.
- Deleted `dataobj` file by running `curl -X DELETE http://localhost:9200/dataobj` from the host machine's terminal. (received the response `{"acknowledged":true}`
- Refresh the page of the application.
- Tried searching for `test` in the search bar. No results.

Here are the logs pertaining to the aforementioned steps:
```
[2020-08-21 03:21:09,937] ERROR in app: Exception on /search [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/main/routes.py", line 107, in search_elastic
    search_results = query_index("dataobj", query)
  File "/usr/src/app/main/search.py", line 20, in query_index
    search = ELASTIC_SEARCH.search(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 92, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 1618, in search
    return self.transport.perform_request(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/transport.py", line 355, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 252, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/connection/base.py", line 281, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [dataobj]', dataobj, index_or_alias)
172.18.0.1 - - [21/Aug/2020 03:21:09] "GET /search?query=t HTTP/1.1" 500 -
[2020-08-21 03:21:10,001] ERROR in app: Exception on /search [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/main/routes.py", line 107, in search_elastic
    search_results = query_index("dataobj", query)
  File "/usr/src/app/main/search.py", line 20, in query_index
    search = ELASTIC_SEARCH.search(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 92, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 1618, in search
    return self.transport.perform_request(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/transport.py", line 355, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 252, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/connection/base.py", line 281, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [dataobj]', dataobj, index_or_alias)
172.18.0.1 - - [21/Aug/2020 03:21:10] "GET /search?query=te HTTP/1.1" 500 -
[2020-08-21 03:21:10,144] ERROR in app: Exception on /search [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/main/routes.py", line 107, in search_elastic
    search_results = query_index("dataobj", query)
  File "/usr/src/app/main/search.py", line 20, in query_index
    search = ELASTIC_SEARCH.search(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 92, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 1618, in search
    return self.transport.perform_request(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/transport.py", line 355, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 252, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/connection/base.py", line 281, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [dataobj]', dataobj, index_or_alias)
172.18.0.1 - - [21/Aug/2020 03:21:10] "GET /search?query=tes HTTP/1.1" 500 -
[2020-08-21 03:21:10,214] ERROR in app: Exception on /search [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/main/routes.py", line 107, in search_elastic
    search_results = query_index("dataobj", query)
  File "/usr/src/app/main/search.py", line 20, in query_index
    search = ELASTIC_SEARCH.search(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 92, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 1618, in search
    return self.transport.perform_request(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/transport.py", line 355, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 252, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/connection/base.py", line 281, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [dataobj]', dataobj, index_or_alias)
172.18.0.1 - - [21/Aug/2020 03:21:10] "GET /search?query=test HTTP/1.1" 500 -
```

Do you want me to run the application in Debug Mode?

**Comment by Uzay-G** [comment]
Sorry, I forgot a few steps in what I asked you last time to try:

1. Delete all of the notes through the ui.
2. do `curl -X DELETE http://localhost:9200/dataobj` to delete the index
3. Close the application `CTRL+C` on the shell.
4. Rerun the application this time

What happens if you try this?

**Comment by HarshaVardhanJ** [comment]
Here's what I did:

- Ran Archivy with Elasticsearch
- Created a note, then tried searching. Same error(s) as before.
- Deleted the note from the UI.
- Ran `curl -X DELETE http://localhost:9200/dataobj` from the host machine(received `{"acknowledged":true}`)
- Killed the container. That stops the processes inside the container.
- Started the container. This restarts the processes inside the container.
- Added a note.
- Tried searching for it.

Here are the logs(from when the process has been restarted):
```
/usr/src/app/entrypoint.sh: line 131: pkill: command not found
Traceback (most recent call last):
  File "check_changes.py", line 2, in <module>
    from main import search, models
  File "/usr/src/app/main/__init__.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
 * Serving Flask app "archivy.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
/usr/local/lib/python3.8/site-packages/scss/selector.py:26: FutureWarning: Possible nested set at position 329
  SELECTOR_TOKENIZER = re.compile(r'''
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
172.18.0.1 - - [21/Aug/2020 08:27:50] "GET /notes/new HTTP/1.1" 200 -
172.18.0.1 - - [21/Aug/2020 08:28:00] "POST /notes/new HTTP/1.1" 302 -
172.18.0.1 - - [21/Aug/2020 08:28:00] "GET /dataobj/1 HTTP/1.1" 200 -
172.18.0.1 - - [21/Aug/2020 08:28:03] "GET /index HTTP/1.1" 200 -
172.18.0.1 - - [21/Aug/2020 08:28:05] "GET /search?query=n HTTP/1.1" 200 -
172.18.0.1 - - [21/Aug/2020 08:28:05] "GET /search?query=ne HTTP/1.1" 200 -
172.18.0.1 - - [21/Aug/2020 08:28:05] "GET /search?query=new HTTP/1.1" 200 -
172.18.0.1 - - [21/Aug/2020 08:30:29] "GET /index HTTP/1.1" 200 -
172.18.0.1 - - [21/Aug/2020 08:30:34] "GET /search?query=n HTTP/1.1" 200 -
172.18.0.1 - - [21/Aug/2020 08:30:37] "GET /search?query=ne HTTP/1.1" 200 -
172.18.0.1 - - [21/Aug/2020 08:30:37] "GET /search?query=new HTTP/1.1" 200 -
```

There doesn't seem to be any relevant logs. I'll try running it in debug mode this time.

**Comment by Uzay-G** [comment]
Could you try adding something to the content of the note and then searching that content. Not `desc` but the content of the markdown file. It could be that it's not searching the fields correctly.
