### ISSUE TITLE
Dockerize application

### ISSUE THREAD

**Issue by Uzay-G** [Uzay-G/archivy#4]

**Comment by HarshaVardhanJ** [comment]
Working on it. Currently running into an issue with installing the required packages via pip. The error message:

```
ERROR: Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from -r requirements.txt (line 24)) (from versions: none)
ERROR: No matching distribution found for pkg-resources==0.0.0 (from -r requirements.txt (line 24))
```

I tried building the file after commenting out the line with the offending package(`pkg-resouces` and the build worked). The issue is similar to [this](https://github.com/pypa/pip/issues/4022) and [this](https://stackoverflow.com/questions/39577984/what-is-pkg-resources-0-0-0-in-output-of-pip-freeze-command). The suggestion being made in both cases is to comment out the line containing `pkg-resources` since it is caused by a bug in Ubuntu and Debian. Any thoughts on this?

**Comment by Uzay-G** [comment]
I tried running the app without the package and had no problems. I just pushed a commit that removes it from the `requirements.txt` and I think running the build without the package is good.

Thanks for helping to dockerize it! (I don't know much about how to build docker images). I'm happy to help with any questions or issues you might have :)

**Comment by HarshaVardhanJ** [comment]
Thank you. I'll create a pull request once the Dockerfile is ready. I've got it to build and run. I'm trying to get the image down to a smaller size.

**Comment by HarshaVardhanJ** [comment]
I've run into an issue while trying to get the Docker image to run. Here is the output of `bash start.sh`:

```
 * Serving Flask app "archivy.py" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with inotify reloader
/usr/local/lib/python3.8/site-packages/scss/selector.py:26: FutureWarning: Possible nested set at position 329
  SELECTOR_TOKENIZER = re.compile(r'''
[2020-08-18 11:10:36,701] INFO in flask_scss: Pyscss loaded!
 * Debugger is active!
 * Debugger PIN: 257-929-719
/usr/local/lib/python3.8/site-packages/scss/selector.py:26: FutureWarning: Possible nested set at position 329
  SELECTOR_TOKENIZER = re.compile(r'''
 * Detected change in '/usr/local/lib/python3.8/site-packages/validators/__pycache__/uuid.cpython-38.pyc', reloading
[2020-08-18 11:10:37,393] INFO in flask_scss: Pyscss loaded!
 * Detected change in '/usr/local/lib/python3.8/site-packages/bs4/__pycache__/__init__.cpython-38.pyc', reloading
 * Detected change in '/usr/local/lib/python3.8/site-packages/bs4/builder/__pycache__/__init__.cpython-38.pyc', reloading
 * Detected change in '/usr/local/lib/python3.8/site-packages/bs4/__pycache__/element.cpython-38.pyc', reloading
 * Detected change in '/usr/local/lib/python3.8/site-packages/bs4/__pycache__/formatter.cpython-38.pyc', reloading
 * Detected change in '/usr/local/lib/python3.8/site-packages/bs4/__pycache__/dammit.cpython-38.pyc', reloading
 * Detected change in '/usr/local/lib/python3.8/site-packages/bs4/builder/__pycache__/_htmlparser.cpython-38.pyc', reloading
 * Detected change in '/usr/local/lib/python3.8/site-packages/bs4/builder/__pycache__/_html5lib.cpython-38.pyc', reloading
 * Detected change in '/usr/local/lib/python3.8/site-packages/bs4/builder/__pycache__/_lxml.cpython-38.pyc', reloading
 * Detected change in '/usr/src/app/main/__pycache__/search.cpython-38.pyc', reloading
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 257-929-719
/usr/local/lib/python3.8/site-packages/scss/selector.py:26: FutureWarning: Possible nested set at position 329
  SELECTOR_TOKENIZER = re.compile(r'''
[2020-08-18 11:10:39,337] INFO in flask_scss: Pyscss loaded!
```

When I try to access `http://localhost:5000/`, there's nothing running on that port. Am I missing something?

**Comment by Uzay-G** [comment]
It should be running... Are you still having this problem?

**Comment by HarshaVardhanJ** [comment]
Same issue. Here's the error message. Seems to be similar to the previous one.

```
 * Serving Flask app "archivy.py" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with inotify reloader
/usr/local/lib/python3.8/site-packages/scss/selector.py:26: FutureWarning: Possible nested set at position 329
  SELECTOR_TOKENIZER = re.compile(r'''
[2020-08-18 13:57:23,513] INFO in flask_scss: Pyscss loaded!
 * Debugger is active!
 * Debugger PIN: 968-916-854
/usr/local/lib/python3.8/site-packages/scss/selector.py:26: FutureWarning: Possible nested set at position 329
  SELECTOR_TOKENIZER = re.compile(r'''
 * Detected change in '/usr/local/lib/python3.8/site-packages/soupsieve/__pycache__/css_types.cpython-38.pyc', reloading
 * Detected change in '/usr/local/lib/python3.8/site-packages/bs4/__pycache__/formatter.cpython-38.pyc', reloading
 * Detected change in '/usr/local/lib/python3.8/site-packages/bs4/__pycache__/dammit.cpython-38.pyc', reloading
 * Detected change in '/usr/local/lib/python3.8/site-packages/bs4/builder/__pycache__/_htmlparser.cpython-38.pyc', reloading
 * Detected change in '/usr/local/lib/python3.8/site-packages/bs4/builder/__pycache__/_html5lib.cpython-38.pyc', reloading
[2020-08-18 13:57:24,618] INFO in flask_scss: Pyscss loaded!
 * Detected change in '/usr/src/app/archivy/main/__pycache__/search.cpython-38.pyc', reloading
 * Detected change in '/usr/local/lib/python3.8/site-packages/bs4/builder/__pycache__/_lxml.cpython-38.pyc', reloading
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 968-916-854
/usr/local/lib/python3.8/site-packages/scss/selector.py:26: FutureWarning: Possible nested set at position 329
  SELECTOR_TOKENIZER = re.compile(r'''
[2020-08-18 13:57:26,934] INFO in flask_scss: Pyscss loaded!
```

Not sure what is causing it. Is there some way I can provide more information to help you debug?

**Comment by HarshaVardhanJ** [comment]
Forgive me if I'm wrong, but I think there might be an issue with the `archivy.py` file. I tried running the `python3.8 archivy.py` directly in the container. Here's the output:
```
(venv) root@5bd0e8275515:/usr/src/app/archivy# python3.8 archivy.py
/usr/local/lib/python3.8/site-packages/scss/selector.py:26: FutureWarning: Possible nested set at position 329
  SELECTOR_TOKENIZER = re.compile(r'''
Traceback (most recent call last):
  File "archivy.py", line 1, in <module>
    from main import app
  File "/usr/src/app/archivy/main/__init__.py", line 40, in <module>
    from main import routes, models
  File "/usr/src/app/archivy/main/routes.py", line 10, in <module>
    from main.models import DataObj
  File "/usr/src/app/archivy/main/models.py", line 8, in <module>
    from main.search import add_to_index
  File "/usr/src/app/archivy/main/search.py", line 1, in <module>
    from main import ELASTIC_SEARCH
ImportError: cannot import name 'ELASTIC_SEARCH' from partially initialized module 'main' (most likely due to a circular import) (/usr/src/app/archivy/main/__init__.py)
```

Is there something I've overlooked?

**Comment by Uzay-G** [comment]
Oh im sorry I pushed a bug recently without realizing it but my last commit just fixed it: https://github.com/Uzay-G/archivy/commit/f9ee6c0ccb75fc5bacdea5497311a05d8b96583e.

Just pull and it should be good.

**Comment by HarshaVardhanJ** [comment]
I tried running `python3.8 archivy.py` again, after pulling the changes made. The program seemed to exit without much output:
```
/usr/local/lib/python3.8/site-packages/scss/selector.py:26: FutureWarning: Possible nested set at position 329
  SELECTOR_TOKENIZER = re.compile(r'''
```

And as before, I'm having the same issue with running `start.sh`.

**Comment by Uzay-G** [comment]
When you run it, does the program end? Also on the last line of `start.sh`, remove `FLASK_DEBUG=1` so the output is less loud.

It's normal that `python3 archivy.py` stopped without running the server but you can try simply running `FLASK_APP=archivy.py flask run` without using the `start.sh`

**Comment by HarshaVardhanJ** [comment]
When I run `FLASK_DEBUG=1 flask run`, the program does not run. The web server seems to keep running, but there does not seem to be anything running in the backend to intercept the requests sent. 

I tried running `FLASK_APP=archivy.py flask run`(after activating the virtual environment). This was the output:

```
 * Serving Flask app "archivy.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
/usr/local/lib/python3.8/site-packages/scss/selector.py:26: FutureWarning: Possible nested set at position 329
  SELECTOR_TOKENIZER = re.compile(r'''
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```

The web server is running, but I'm unable to access the application.

**Comment by Uzay-G** [comment]
Are you running this locally? If you're accessing a remote server with a public ip maybe see this SO answer: https://stackoverflow.com/questions/30554702/cant-connect-to-flask-web-service-connection-refused

You can try running `FLASK_APP=archivy.py flask run --host=0.0.0.0`

**Comment by HarshaVardhanJ** [comment]
Bingo. I was building and running the container locally, but with the way Docker works, the requests were not being sent to the application, which was listening on localhost *inside* the container. Here's a [link])(https://pythonspeed.com/articles/docker-connection-refused/) that describes this. Thanks!

**Comment by Uzay-G** [comment]
Yeah ok!

**Comment by HarshaVardhanJ** [comment]
Added Dockerfiles! Created PR.

**Comment by HarshaVardhanJ** [comment]
@Uzay-G This issue can be closed now, yes?

**Comment by Uzay-G** [comment]
Yup!
