### ISSUE TITLE
OSError: [Errno 48] Address already in use

### ISSUE THREAD

**Issue by dxcore35** [Uzay-G/archivy#46]
```
/bin/sh: service: command not found
Enter password to enable elasticsearch
sudo: service: command not found
Elasticsearch index already created
 * Serving Flask app "archivy" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/usr/local/bin/archivy", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/archivy/run.py", line 8, in main
    app.run(host='0.0.0.0')
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 1005, in inner
    fd=fd,
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 848, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 48] Address already in use
```

**Comment by srevinsaju** [comment]
It looks like some other process is running on port 5000, can you restart you computer and try again. Meanwhile, this should be fixed by using random port numbers in the range 10000-18000 where it's uncommon for system processes to use as ports

**Comment by HarshaVardhanJ** [comment]
If you're running this on Linux, try running
```sh
netstat -tulpn | grep "5000"
```

This should show you which process is running on port 5000. If you wish to(although not advisable), you can kill the process using
```sh
kill [PID of process]
```

**Comment by HarshaVardhanJ** [comment]
> It looks like some other process is running on port 5000, can you restart you computer and try again. Meanwhile, this should be fixed by using random port numbers in the range 10000-18000 where it's uncommon for system processes to use as ports

Or the port number could be user-configurable similar to the directory in which data is saved. Maybe a variable like `LISTEN_PORT` could be provided.

**Comment by Uzay-G** [comment]
Reopen the issue if it's still not working :smile:
