### ISSUE TITLE
Archivy tries to connect to Elasticsearch even though `ELASTICSEARCH_ENABLED=0`

### ISSUE THREAD

**Issue by HarshaVardhanJ** [Uzay-G/archivy#47]
Archivy tries to connect to Elasticsearch even if the `ELASTICSEARCH_ENABLED` variable is set to `0`, and results in the following error when I try to create a note.
```
elasticsearch: unrecognized service
Enter password to enable elasticsearch
/bin/sh: 1: sudo: not found
Elasticsearch index already created
 * Serving Flask app "archivy" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with inotify reloader
elasticsearch: unrecognized service
Enter password to enable elasticsearch
/bin/sh: 1: sudo: not found
Elasticsearch index already created
 * Debugger is active!
 * Debugger PIN: 278-421-703
172.17.0.1 - - [25/Aug/2020 08:55:05] "POST /notes/new HTTP/1.1" 200 -
Changes to /root/.local/share/archivy/data/7-08-25-20-Test_Note.md
Changes to /root/.local/share/archivy/data/7-08-25-20-Test_Note.md
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/root/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/root/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 228, in perform_request
    response = self.pool.urlopen(
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/root/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/root/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 228, in perform_request
    response = self.pool.urlopen(
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/root/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 379, in increment
  File "/root/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 379, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/.local/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/.local/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.8/http/client.py", line 1010, in _send_output
  File "/usr/local/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/root/.local/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/root/.local/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
    self.send(msg)
  File "/usr/local/lib/python3.8/http/client.py", line 950, in send
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f203ec824f0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/root/.local/lib/python3.8/site-packages/watchdog/observers/api.py", line 203, in run
    self.dispatch_events(self.event_queue, self.timeout)
  File "/root/.local/lib/python3.8/site-packages/watchdog/observers/api.py", line 376, in dispatch_events
    handler.dispatch(event)
  File "/root/.local/lib/python3.8/site-packages/watchdog/events.py", line 331, in dispatch
    self.connect()
  File "/root/.local/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/root/.local/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f690ced0670>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    {
  File "/root/.local/lib/python3.8/site-packages/archivy/check_changes.py", line 17, in on_modified
    search.add_to_index(Config.INDEX_NAME, dataobj)
  File "/root/.local/lib/python3.8/site-packages/watchdog/observers/api.py", line 203, in run
  File "/root/.local/lib/python3.8/site-packages/archivy/search.py", line 12, in add_to_index
    ELASTICSEARCH.index(index=index, id=model.id, body=payload)
  File "/root/.local/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 92, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 404, in index
    return self.transport.perform_request(
    self.dispatch_events(self.event_queue, self.timeout)
  File "/root/.local/lib/python3.8/site-packages/watchdog/observers/api.py", line 376, in dispatch_events
    handler.dispatch(event)
  File "/root/.local/lib/python3.8/site-packages/elasticsearch/transport.py", line 355, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/root/.local/lib/python3.8/site-packages/watchdog/events.py", line 331, in dispatch
  File "/root/.local/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 241, in perform_request
    raise ConnectionError("N/A", str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f203ec824f0>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f203ec824f0>: Failed to establish a new connection: [Errno 111] Connection refused)
    {
  File "/root/.local/lib/python3.8/site-packages/archivy/check_changes.py", line 17, in on_modified
    search.add_to_index(Config.INDEX_NAME, dataobj)
  File "/root/.local/lib/python3.8/site-packages/archivy/search.py", line 12, in add_to_index
    ELASTICSEARCH.index(index=index, id=model.id, body=payload)
  File "/root/.local/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 92, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 404, in index
    return self.transport.perform_request(
  File "/root/.local/lib/python3.8/site-packages/elasticsearch/transport.py", line 355, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/root/.local/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 241, in perform_request
    raise ConnectionError("N/A", str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f690ced0670>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f690ced0670>: Failed to establish a new connection: [Errno 111] Connection refused)
172.17.0.1 - - [25/Aug/2020 08:55:08] "POST /notes/new HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/root/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/root/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 228, in perform_request
    response = self.pool.urlopen(
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/root/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 379, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/.local/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/root/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/root/.local/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/root/.local/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f690ced02e0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/.local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/root/.local/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/.local/lib/python3.8/site-packages/archivy/routes.py", line 64, in new_note
    note_id = note.insert()
  File "/root/.local/lib/python3.8/site-packages/archivy/models.py", line 122, in insert
    add_to_index(Config.INDEX_NAME, self)
  File "/root/.local/lib/python3.8/site-packages/archivy/search.py", line 12, in add_to_index
    ELASTICSEARCH.index(index=index, id=model.id, body=payload)
  File "/root/.local/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 92, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 404, in index
    return self.transport.perform_request(
  File "/root/.local/lib/python3.8/site-packages/elasticsearch/transport.py", line 355, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/root/.local/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 241, in perform_request
    raise ConnectionError("N/A", str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f690ced02e0>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f690ced02e0>: Failed to establish a new connection: [Errno 111] Connection refused)
```

This happens when `ELASTICSEARCH_ENABLED` is set to either `0` or `1`. The program works as expected only if the `ELASTICSEARCH_ENABLED` variable is unset.

**Comment by Uzay-G** [comment]
Thanks for finding this! I just fixed it here: https://github.com/Uzay-G/archivy/commit/e49c5ebe6a7cba8222b30087eeef6b580e0dcd34 and pushed to the new release. Update your package for the fix.

**Comment by HarshaVardhanJ** [comment]
That was quick! Thanks!

**Comment by Uzay-G** [comment]
Yeah it's an important bug :smile:
